# -*- coding: utf-8 -*-
"""contact_book.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-jyEb_gksWS5d6r7HBjkQcKFbgPs1xo7
"""

def contact_book():
    contacts = {}

    while True:
        print("\n Contact Book")
        print("1. Add Contact")
        print("2. View Contacts")
        print("3. Search Contact")
        print("4. Delete Contact")
        print("5. Exit")

        choice = input("Enter your choice (1-5): ")

        if choice == "1":
            name = input("Enter name: ")
            phone = input("Enter phone number: ")
            contacts[name] = phone
            print("Contact added successfully!")

        elif choice == "2":
            if contacts:
                print("\nSaved Contacts:")
                for name, phone in contacts.items():
                    print(f"{name} : {phone}")
            else:
                print("No contacts found.")

        elif choice == "3":
            name = input("Enter name to search: ")
            if name in contacts:
                print(f"{name}'s number is {contacts[name]}")
            else:
                print("Contact not found.")

        elif choice == "4":
            name = input("Enter name to delete: ")
            if name in contacts:
                del contacts[name]
                print("Contact deleted successfully.")
            else:
                print("Contact not found.")

        elif choice == "5":
            print("Exiting Contact Book.")
            break

        else:
            print("Invalid choice. Please try again.")

contact_book()